name: Check

on: [pull_request]

jobs:
  check:
    name: Install and package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install and package
        run: |
          yarn install
          yarn run package


